<a href="https://colab.research.google.com/github/mishrapranjal879/PythonCodesForPractice/blob/main/class3file.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Numpy array operations

Lets first see how arrays behave like “vectors/matrices” when operations happen element-wise.

In [4]:
import numpy as np
a = np.array([10,20,30,40])
b = np.array([1,2,3,4])
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[11 22 33 44]
[ 9 18 27 36]
[ 10  40  90 160]
[10. 10. 10. 10.]


These things are already different from List and if we talk about one more special power it is **Broadcasting**

In [5]:
a = np.array([1,2,3,4])
print(a*2)

[2 4 6 8]


Even these things work with different shaped array the calculations will happen on every row. but dimensions must match

In [10]:
arr = np.array([[1,2,3,4],[4,5,6,7]])
print(arr*5)

[[ 5 10 15 20]
 [20 25 30 35]]


#Aggregate Functions

These functions are used to calculate the statistics on arrays.

In [12]:
arr = np.array([[1,2,3,4],[4,5,6,7]])
print(np.sum(arr))
print(np.mean(arr))
print(np.min(arr))
print(np.max(arr))
print(np.std(arr))
print(np.var(arr))

32
4.0
1
7
1.8708286933869707
3.5


You can also do the axis based operations row-Wise and Colum-wise

In [14]:
data = np.array([[1,2,3,4],[4,5,6,7]])
print(np.sum(data,axis=0))
print(np.sum(data,axis=1))
print(np.mean(data,axis=0))
print(np.mean(data,axis=1))

[ 5  7  9 11]
[10 22]
[2.5 3.5 4.5 5.5]
[2.5 5.5]
