<a href="https://colab.research.google.com/github/mishrapranjal879/PythonCodesForPractice/blob/main/class4file.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Fancy Indexing
you can Pick elements from specific positions using a list/array of indices.

In [2]:
import numpy as np
arr = np.array([10,20,30,40,50,60])
arr[[0,2,4]]

array([10, 30, 50])

You can do this fancy indexing in 2D Matrix aswell

In [4]:
matrix = np.arange(1,13).reshape(3,4)
print(matrix)
matrix[[0,1],[1,2]]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


array([2, 7])

##Conditional Selection
Find values based on conditions or replace them.

In [8]:
arr = np.array([5,23,67,98])
arr[arr>10]
np.where(arr>10)

np.where(arr>10,arr,0)


array([ 0, 23, 67, 98])

##Sorting & Ordering
np.sort() → returns sorted array

np.argsort() → returns indices of sorted order

In [10]:
arr = np.array([5,23,67,98])
np.sort(arr)


array([ 5, 23, 67, 98])

In [11]:
np.argsort(arr)

array([0, 1, 2, 3])

##Concatenation & Stacking

In [12]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
np.concatenate([a,b])

array([1, 2, 3, 4, 5, 6, 7, 8])

Vertical & Horizontal Stacking

In [14]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
np.vstack([B,A])

array([[5, 6],
       [7, 8],
       [1, 2],
       [3, 4]])

In [15]:
np.hstack([B,A])

array([[5, 6, 1, 2],
       [7, 8, 3, 4]])

In [16]:
np.concat([A,B])

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])