In [ ]:
import torch

In [8]:
torch.tensor([1,2,3,4,5])

tensor([1, 2, 3, 4, 5])

In [7]:
x=torch.tensor([[1,2,3],[4,5,6]])

In [9]:
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [11]:
x=torch.rand(2,2)
x

tensor([[0.3541, 0.6475],
        [0.8872, 0.3846]])

In [12]:
x+2

tensor([[2.3541, 2.6475],
        [2.8872, 2.3846]])

In [13]:
x-2

tensor([[-1.6459, -1.3525],
        [-1.1128, -1.6154]])

In [14]:
x*3

tensor([[1.0622, 1.9425],
        [2.6617, 1.1539]])

In [15]:
x/3

tensor([[0.1180, 0.2158],
        [0.2957, 0.1282]])

In [16]:
(x*100)//3

tensor([[11., 21.],
        [29., 12.]])

In [17]:
((x*100)//3)%2

tensor([[1., 1.],
        [1., 0.]])

In [31]:
y=torch.tensor([[10,20,30],[40,50,60]])
y

tensor([[10, 20, 30],
        [40, 50, 60]])

In [30]:
z=torch.tensor([[2,2,7],[8,6,7]])
z

tensor([[2, 2, 7],
        [8, 6, 7]])

In [28]:
y+z

tensor([[12, 22, 37],
        [48, 56, 67]])

In [29]:
y-z

tensor([[ 8, 18, 23],
        [32, 44, 53]])

In [32]:
torch.neg(y)

tensor([[-10, -20, -30],
        [-40, -50, -60]])

In [33]:
torch.round(x)

tensor([[0., 1.],
        [1., 0.]])

In [35]:
d=torch.tensor([1.9,2.3,3.7,4.4])
d

tensor([1.9000, 2.3000, 3.7000, 4.4000])

In [36]:
torch.floor(d)

tensor([1., 2., 3., 4.])

In [37]:
torch.clamp(d, min=2, max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

In [38]:
e=torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

tensor([[3., 7., 2.],
        [0., 2., 2.]])

In [40]:
f=torch.randint(size=(2,3), low=0, high=10)
g=torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)

tensor([[7, 0, 7],
        [7, 6, 1]])
tensor([[3, 1],
        [5, 7],
        [6, 4]])


In [43]:
torch.matmul(f,g)

tensor([[63, 35],
        [57, 53]])